# Generated by Django 4.2.1 on 2023-05-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_user', '0002_user_delete_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_usuario',
            new_name='id_user',
        ),
    ]
