# Generated by Django 4.2.1 on 2023-06-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_user', '0003_rename_id_usuario_user_id_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_aula1',
        ),
    ]
